// Code generated by "stringer -type=Token"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tMemSize-0]
	_ = x[tDefense-1]
	_ = x[TOffense-2]
	_ = x[tSize-3]
	_ = x[tEnergy-4]
	_ = x[tPass-5]
	_ = x[tPosture-6]
	_ = x[tComment-7]
	_ = x[tComm-8]
	_ = x[tAssign-9]
	_ = x[tLequ-10]
	_ = x[tGequ-11]
	_ = x[tNequ-12]
	_ = x[tMem-13]
	_ = x[tWait-14]
	_ = x[tForward-15]
	_ = x[tBackward-16]
	_ = x[tLeft-17]
	_ = x[tRight-18]
	_ = x[tEat-19]
	_ = x[tAttack-20]
	_ = x[tGrow-21]
	_ = x[tBud-22]
	_ = x[tServe-23]
	_ = x[tNearby-24]
	_ = x[tAhead-25]
	_ = x[tRandom-26]
	_ = x[tSmell-27]
	_ = x[tAnd-28]
	_ = x[tOr-29]
	_ = x[tMod-30]
	_ = x[tStar-31]
	_ = x[tDiv-32]
	_ = x[tPlus-33]
	_ = x[tMinus-34]
	_ = x[tLess-35]
	_ = x[tGreat-36]
	_ = x[tEqu-37]
	_ = x[tLParen-38]
	_ = x[tRParen-39]
	_ = x[tLBracket-40]
	_ = x[tRBracket-41]
	_ = x[tLBrace-42]
	_ = x[tRBrace-43]
	_ = x[tSemicolon-44]
	_ = x[tNumber-45]
	_ = x[tWS-46]
	_ = x[tMismatch-47]
	_ = x[tNone-48]
}

const _Token_name = "tMemSizetDefenseTOffensetSizetEnergytPasstPosturetCommenttCommtAssigntLequtGequtNequtMemtWaittForwardtBackwardtLefttRighttEattAttacktGrowtBudtServetNearbytAheadtRandomtSmelltAndtOrtModtStartDivtPlustMinustLesstGreattEqutLParentRParentLBrackettRBrackettLBracetRBracetSemicolontNumbertWStMismatchtNone"

var _Token_index = [...]uint16{0, 8, 16, 24, 29, 36, 41, 49, 57, 62, 69, 74, 79, 84, 88, 93, 101, 110, 115, 121, 125, 132, 137, 141, 147, 154, 160, 167, 173, 177, 180, 184, 189, 193, 198, 204, 209, 215, 219, 226, 233, 242, 251, 258, 265, 275, 282, 285, 294, 299}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
