// Code generated by "stringer -type=Token"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_MEMSIZE-0]
	_ = x[T_DEFENSE-1]
	_ = x[T_OFFENSE-2]
	_ = x[T_SIZE-3]
	_ = x[T_ENERGY-4]
	_ = x[T_PASS-5]
	_ = x[T_POSTURE-6]
	_ = x[T_COMMENT-7]
	_ = x[T_COMM-8]
	_ = x[T_ASSIGN-9]
	_ = x[T_LEQU-10]
	_ = x[T_GEQU-11]
	_ = x[T_NEQU-12]
	_ = x[T_MEM-13]
	_ = x[T_WAIT-14]
	_ = x[T_FORWARD-15]
	_ = x[T_BACKWARD-16]
	_ = x[T_LEFT-17]
	_ = x[T_RIGHT-18]
	_ = x[T_EAT-19]
	_ = x[T_ATTACK-20]
	_ = x[T_GROW-21]
	_ = x[T_BUD-22]
	_ = x[T_SERVE-23]
	_ = x[T_NEARBY-24]
	_ = x[T_AHEAD-25]
	_ = x[T_RANDOM-26]
	_ = x[T_SMELL-27]
	_ = x[T_AND-28]
	_ = x[T_OR-29]
	_ = x[T_MOD-30]
	_ = x[T_STAR-31]
	_ = x[T_DIV-32]
	_ = x[T_PLUS-33]
	_ = x[T_MINUS-34]
	_ = x[T_LESS-35]
	_ = x[T_GREAT-36]
	_ = x[T_EQU-37]
	_ = x[T_L_PAREN-38]
	_ = x[T_R_PAREN-39]
	_ = x[T_L_BRACKET-40]
	_ = x[T_R_BRACKET-41]
	_ = x[T_L_BRACE-42]
	_ = x[T_R_BRACE-43]
	_ = x[T_SEMICOLON-44]
	_ = x[T_NUMBER-45]
	_ = x[T_WS-46]
	_ = x[T_MISMATCH-47]
	_ = x[T_NONE-48]
}

const _Token_name = "T_MEMSIZET_DEFENSET_OFFENSET_SIZET_ENERGYT_PASST_POSTURET_COMMENTT_COMMT_ASSIGNT_LEQUT_GEQUT_NEQUT_MEMT_WAITT_FORWARDT_BACKWARDT_LEFTT_RIGHTT_EATT_ATTACKT_GROWT_BUDT_SERVET_NEARBYT_AHEADT_RANDOMT_SMELLT_ANDT_ORT_MODT_START_DIVT_PLUST_MINUST_LESST_GREATT_EQUT_L_PARENT_R_PARENT_L_BRACKETT_R_BRACKETT_L_BRACET_R_BRACET_SEMICOLONT_NUMBERT_WST_MISMATCHT_NONE"

var _Token_index = [...]uint16{0, 9, 18, 27, 33, 41, 47, 56, 65, 71, 79, 85, 91, 97, 102, 108, 117, 127, 133, 140, 145, 153, 159, 164, 171, 179, 186, 194, 201, 206, 210, 215, 221, 226, 232, 239, 245, 252, 257, 266, 275, 286, 297, 306, 315, 326, 334, 338, 348, 354}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
